---
- name: Install apache2
  apt:
    name:
      - apache2
    state: present

- name: Install PHP-FPM
  apt:
    name:
      - php-fpm
    state: present

- name: Install apache fast-cgi
  apt:
    deb: "https://mirrors.edge.kernel.org/ubuntu/pool/\
    multiverse/liba/libapache-mod-fastcgi/\
    libapache2-mod-fastcgi_2.4.7~0910052141-1.2_amd64.deb"
